
-- Master task repository: global knowledge base of construction tasks
CREATE TABLE public.master_tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  normalized_name text NOT NULL UNIQUE,
  tags text[] DEFAULT '{}',
  category text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Subtasks generated by AI for each master task
CREATE TABLE public.master_subtasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  master_task_id uuid NOT NULL REFERENCES public.master_tasks(id) ON DELETE CASCADE,
  name text NOT NULL,
  sort_order integer DEFAULT 0,
  category text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- RLS: all authenticated users can read (global knowledge base)
ALTER TABLE public.master_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_subtasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view master tasks" ON public.master_tasks FOR SELECT TO authenticated USING (true);
CREATE POLICY "Anyone can view master subtasks" ON public.master_subtasks FOR SELECT TO authenticated USING (true);

CREATE INDEX idx_master_tasks_normalized_name ON public.master_tasks(normalized_name);
CREATE INDEX idx_master_subtasks_master_task_id ON public.master_subtasks(master_task_id);
